HOSTS:
  ubuntu-server-12042-x64:
    roles:
      - master
    platform: ubuntu-12.04-amd64
    box : ubuntu-server-12042-x64-vbox4210-nocm
    box_url : https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
    hypervisor : vagrant
CONFIG:
  type: foss
